version: '3.7'

services:
  mongo_db:
    image: mongo:4.2.12
    ports:
      - 27017:27017
#    deploy:
 #     replicas: 2  # Adjust as needed for your Raspberry Pi nodes

    volumes:
      - /C/Mine/mongoData:/data/db

  mongo_express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mongo_db
